version: "3"
services:

  streamlit:
    build: streamlit/
    ports:
      - "8501:8501"
    # networks:
    #   - deploy_network
    container_name: streamlit_bigdata



# networks:
#   deploy_network:
#     driver: bridge
    